image: dpotter/pkdgrav3-build

pipelines:
  default:
    - step:
        script:
          - cmake .
          - make
  branches:
     IA_dev_optim:
       - step:
           script:
             - >
               cmake -DCOOLING=on
               -DSTAR_FORMATION=on
               -DFEEDBACK=on
               -DEEOS_POLYTROPE=on
               -DBLACKHOLES=on
               -DSTELLAR_EVOLUTION=on
               .
             - make
