#!/bin/bash
# This hook is installed automatically by CMake if a git repository is detected in
# the source directory. To install it manually you can create a symbolic link,
# normally something like
#     ln -s ../../git-pre-commit-hook .git/hooks/pre-commit
# Pull requests with code not properly formatted will be rejected!

RETURN=0
test -z "$ASTYLE" && ASTYLE=astyle
ASTYLE=$(which $ASTYLE)
if [ $? -ne 0 ]; then
	echo "[!] astyle not installed. Unable to check source file format policy." >&2
	echo "Ubuntu: sudo apt install astyle" >&2
	echo "macOS: brew install astyle" >&2
	echo "or download from http://astyle.sourceforge.net" >&2
	exit 1
fi

FILES=`git diff --cached --name-only --diff-filter=ACMR | egrep -v '^(mdl2/(openpa|boost)|fmt|blitz|windows)/' | egrep '\.(c|h|cxx|mm|metal|cu)$'`
for FILE in $FILES; do
	$ASTYLE --project --stdin=$FILE | cmp -s $FILE -
	if [ $? -ne 0 ]; then
		echo "[!] $FILE does not respect the agreed coding style." >&2
		RETURN=1
	fi
done

if [ $RETURN -eq 1 ]; then
	echo "" >&2
	echo "Make sure you have run astyle with the following options:" >&2
	echo $ASTYLE --project >&2
fi

exit $RETURN
